[build]
  command = "CI= pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22.0.0"
  PNPM_VERSION = "7.33.7"
  COREPACK_ENABLE_STRICT = "0"
